cos/urls.py
from django.urls import path


from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.chamber, name='chamber'),
    path('secrets/', views.secrets, name='secrets'),
    
    # ex: /polls/5/
#    path('<int:joke_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
#    path('<int:joke_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
#    path('<int:joke_id>/vote/', views.vote, name='vote'),
    
    
#    path('stupidstuff/', views.stupidstuff, name='stupidstuff'),
#    path('test/', views.test, name='test'),
#    path('taste/', views.taste, name='taste'),
#    path('ttaste/', views.ttaste, name='ttaste'),
#    path('uploadJokeView/', views.uploadJokeView, name='uploadJokeView'),
]

jokeleopedia/urls.py
from django.contrib import admin
from django.urls import path, include

# For user authentication (login/logout)
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView 
from jokes.views import vote as j, index

from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap, LoginViewSitemap, EachJokes

sitemaps = {
    'static': StaticViewSitemap,
    'login':LoginViewSitemap,
    'each_jokes':EachJokes,
}

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jokes.urls')),
    path('jokes/', include('jokes.urls')),
    path('vote/', j, name='vote'),
    #path('ariesap', include('ariesap.urls')),
    #path('memmes/', include('memmes.urls')),
    path('memes/', include('memes.urls')),
    path('user/', include('user.urls')),
    #path('searchtest/', include('searchtest.urls')),
    path('register/', views.Join, name='join'),    
    path('login/', auth_views.LoginView.as_view(), name='Login'),
    #path('register/', auth_views.RegisterView.as_view(), name='Register'),
    path('logout/', auth_views.LogoutView.as_view(), name='Logout'),
    
    #path('category/', views.categories, name='category'),
    
    #path('accounts/password_reset/done/', name='password_reset_done'),
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='logout'),
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    #path('', index, name='index'),
    path('chit-chat/', include('chat.urls')),
    path('cos/',include('cos.urls')),
    path('tu/',include('hotornot.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}),
]




#The URLs provided by auth are:
'''
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']
Source:https://learndjango.com/tutorials/django-login-and-logout-tutorial
'''

user/urls.py
from django.urls import path


from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.Profile, name='profile'),
    path('uploadprofilepic/', views.UploadProfileView, name='upload_profile_pic'),
    path('categories/', views.categoriesView, name='categories'),
    path('info/', views.getUserDataView, name='info'),
    # ex: /polls/5/
    #path('<int:joke_id>/', views.detail, name='detail'),
]

user/models.py
from django.db import models
#from django.db import PositiveBigIntegerField

# Create your models here.
import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.fields import ArrayField
import uuid

#######////////////////// Ommit Comment \\\\\\\\\\\\\\\#########  
#@login_required
class ProfilePicModel(models.Model):
    image = models.FileField(upload_to='user/static/user/profile_pics')
    pub_date = models.DateTimeField('date published', default=timezone.now)

#######////////////////// Ommit Comment \\\\\\\\\\\\\\\#########  
#@login_required
class User(models.Model):
    username = models.CharField(max_length = 50, primary_key=True)#one to one key with request.user.username
    first_name = models.CharField(max_length = 50, default=None, null=True)
    middle_name = models.CharField(max_length = 50, default=None, null=True)
    last_name = models.CharField(max_length = 50, default=None, null=True)
    preferred_categories = ArrayField(models.CharField(max_length=250, blank=True), default=None, null=True)
    email = models.EmailField()
    her_country = models.CharField(max_length=60, default = None, null=True)
    phone_number = models.BigIntegerField(default=0,)
    relligion = models.CharField(max_length = 50)
    profile_url = models.CharField(max_length = 100, default='')
    profile_pic = models.FileField(upload_to='user/static/user/images',null=True)

class ModelWithFileField(models.Model):
    title = models.CharField(max_length=50)
    filez = models.FileField(upload_to='jokes/static/jokes/images')
    #class Mete:
     #   db_table='chuckles'

'''
Post is the name of model
>>> Post.objects.create(name='Third post', tags=['tutorial', 'django'])

>>> Post.objects.filter(tags__contains=['thoughts'])'''

jokes/forms.py
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm
from .models import UploadJokes, SearchModel
from django import forms

class UploadJokeForm(ModelForm):
    class Meta:
        exclude = ('votes', 'rating','tag', 'shares','pub_date')
        model = UploadJokes
        fields = '__all__'
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

class SearchForm(ModelForm):
    search_term = forms.CharField(max_length=100)
    class Meta:
        model = SearchModel
        fields = '__all__'
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }
#class ContactForm(forms.Form):
 #   subject = forms.CharField(max_length=100)
  #  message = forms.CharField(widget=forms.Textarea)
   # sender = forms.EmailField()
    #cc_myself = forms.BooleanField(required=False)
    

#class commentform(forms.Form):
#    comment = forms.CharField(max_length=100)

class sendMailForm(forms.Form):
    #Your_email_address = forms.EmailField()
    #message = forms.CharField(label='message', max_length = 1000)
    #summary = forms.CharField(max_length = 100)
    ananomyous_username = forms.CharField(label='ananomyous_username', max_length = 50)
    body = forms.CharField(label='body', max_length = 500)
    email = forms.EmailField()

user/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS

from .models import ProfilePicModel


class ProfilePicForm(ModelForm):
    #meme = forms.FileField(label='Select a file', help_text='max. 42 megabytes')
    class Meta:
        model = ProfilePicModel
        fields = '__all__'
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

user/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ProfilePicForm
from .models import ProfilePicModel, User
from jokes.models import WockaJokes
from jokes.views import index
from django.db.utils import DataError

from django.contrib.auth.decorators import login_required
import os

# Create your views here.

def UploadProfileView(request):
    if request.method == 'POST':
        form = ProfilePicForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            doc_to_save = request.FILES['image']
            filename = doc_to_save._get_name()
            return redirect(Profile)
            #return HttpResponse(filename)
 #       else:
#            return HttpResponse('Invalid Form')
    else:
        form = ProfilePicForm()
        return render(request, 'memes/index.html', {'form': form,'display_type':'/Upload/' })
#
def Profile(request):
    latest_profile_pic = ProfilePicModel.objects.order_by('-pub_date')[:1]
    for i in latest_profile_pic:
        latest_profile_pic = str(i.image).replace('user/static/','')
    

    #######////////////////// Change This to get real user detail \\\\\\\\\\\\\\\#########    

    user = User.objects.get(id=1)

    #######//////////////////Change This \\\\\\\\\\\\\\\#########
    
    
    return render(request, 'user/profile.html', {'profile_pic':latest_profile_pic,'user':user})

@login_required
def categoriesView(request):
    categories = [category['category'] for category in WockaJokes.objects.values('category').distinct()]
    #return HttpResponse(categories)
    if (request.user.is_authenticated):
        #return HttpResponse('HEllo' + request.user.username)
        username = request.user.username
    #try:
    user = User.objects.get(username=username)
    #Categories saved in user's database
    
    pre_selected_categories = user.preferred_categories
    if pre_selected_categories:
        unselected_categories=[i for i in categories if i not in pre_selected_categories]
    else:
        unselected_categories=categories
    if request.method == 'POST':
        #return HttpResponse('Purnika')
    #if form.is_valid():
        selected_categories = request.POST.get('selectedCategories')


        userSelectedCategories=[]
        for category in categories:
            #return HttpResponse(request.POST.get(category))
            if (request.POST.get(category)!=None):
                #return HttpResponse('Purnika')
                #return HttpResponse(str(category.value()))
                userSelectedCategories.append(str(category))
            #return HttpResponse('She is waiting. hurry up! ' + str(user))
        #    user = User(preferred_categories = userSelectedCategories)
        #    print(str(err))
        user.preferred_categories = userSelectedCategories
        user.save()
        #return HttpResponse('saved:\n\n'+str(userSelectedCategories))
        
        #user.save()
        #return HttpResponse(password)
        return redirect(index)
        #return render(request, 'jokes/index.html', {'message':'Account Created!'})

            #return render(request, 'jokes/login.html', {'RegisterErrorMessage':'Sorry! username already taken', 'authtype':'/Register/'})
    else:
        #return HttpResponse(str(unselected_categories))
        return render(request, 'user/pre_home_page.html',{'unselected_categories':unselected_categories,'pre_selected_categories':pre_selected_categories})



@login_required
def getUserDataView(request):
    if (request.user.is_authenticated):
        #return HttpResponse('HEllo' + request.user.username)
        username = request.user.username
    else:
        test=1
        #Code For Testing user is loggged in
        return HttpResponse('user/viwes.py line 102: Code For Testing user is loggged in')

    try:
        #Try because User table of logged in user is not created at first 
        user = User.objects.get(username=username)
        #return HttpResponse('Hello')
    except User.DoesNotExist as err:
        user = User(username=username)
        user.save()

    if request.method == 'POST':
        form = ProfilePicForm
        if form.is_valid():
            
        
        #return HttpResponse('Hello From Purnika!')
        #if form.is_valid():
            first_name = request.POST.get('first_name')
            middle_name = request.POST.get('middle_name')
            last_name = request.POST.get('last_name')
            email = request.POST.get('email')
            phone_number = request.POST.get('phone_number')
            relligion = request.POST.get('relligion')
            country = request.POST.get('country')
            user.first_name=first_name
            user.middle_name=middle_name
            user.last_name=last_name
            user.email=email
            user.phone_number=phone_number
            user.relligion = relligion
            user.her_country = country
            try:
                user.save()
            except DataError as err:
                #print(str(err))
                return render(request, 'user/pre_home_page.html',{'getUSerInfo':True,  'user':user,'message':'Please enter a valid phone number'})
            return redirect(categoriesView)
            
            #return HttpResponse('Saved: '+str(first_name)+str(middle_name)+str(last_name)+str(email)+str(phone_number)+str(relligion))
        
            #user.save()
            #return HttpResponse(password)
            #return render(request, 'jokes/mermaid.html', {'message':'Account Created!'})
            
                #return render(request, 'jokes/login.html', {'RegisterErrorMessage':'Sorry! username already taken', 'authtype':'/Register/'})
        else:
            #return HttpResponse('Purnika')
            return render(request, 'user/pre_home_page.html',{'getUSerInfo':True, 'user':user})
            
            







            #return HttpResponse('Purnika')
        
            '''
        
        
        
        
        
        
            if request.method == 'POST':
        upload_form = UploadMemeForm(request.POST, request.FILES)
        if upload_form.is_valid():
            meme=upload_form.save()
            #return HttpResponse(str(m.meme))
            doc_to_save = request.FILES['meme']
            #return HttpResponse(doc_to_save)
            filename = doc_to_save._get_name()
            #return HttpResponse(filename)
            client_id = '55d759dcb713183'
            client_secret = '3c2a1cf3af3422b25206ef718f191ea5a6ca8c82'
            print("\n\n\n Logging in ")
            client = ImgurClient(client_id, client_secret)
            print(" Logged in \n")
            album = None
            #return HttpResponse('memes/static/memes/images/'+str(filename))
            #meme = UploadMeme.objects.get(meme='memes/static/memes/images/'+str(filename))
            image_path = str(meme.meme)     #Because it returns FileField
            description ='test description'
            #name = str(meme.meme).split('/')[-1]
            config={
                "album":None,
                "name": filename,
                "title": request.POST.get('title'),
                "description": request.POST.get('description'),
            }
            print('\n\n\n Uploading \n\n\n' + str(meme))
            image=client.upload_from_path(image_path, config=config, anon=True)
            print(' path: ' + str(image['link']))
            
            meme.src=image['link']
            meme.save()
            os.remove(str(meme.meme))              #removing file from local directory
        
        
        '''
        
        
        
        
        
            
'''except Exception as ex:
            test=1
            #Code for testing What error has occoured
            return HttpResponse(str(ex)+'user/viwes.py line 118: Code For Testing user is loggged in')'''

        #return HttpResponse('Hello')
        #except 

user/templates/user/pre_home_page.html
<style>
.visuallyhidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}

/*
 * Extends the .visuallyhidden class to allow the element to be focusable
 * when navigated to via the keyboard: h5bp.com/p
 */

.visuallyhidden.focusable:active,
.visuallyhidden.focusable:focus {
    clip: auto;
    height: auto;
    margin: 0;
    overflow: visible;
    position: static;
    width: auto;
}


if you want your check box to keep its height and width but only be invisible:

.hiddenCheckBox{
    visibility: hidden;
}

if you want your check box to be invisible without any with and height:

.hiddenCheckBox{
    display: none;
}

###########################################################
implement javascript to make bold and change circle colour when checked
</style>












{%if unselected_categories %}



<H1>Categories:</h1>

<form action="/user/categories/" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ upload_form }}

  {% for category in unselected_categories %}
  <input type="checkbox" id="{{category}}" name="{{category}}" value="{{category}}" style="opacity:0;/* position:absolute; left:9999px;*/">
  <label for="{{category}}"> {{ category }}</label><br>
  {% endfor %}

  {% for category in pre_selected_categories %}
  <input type="checkbox" id="{{category}}" name="{{category}}" value="{{category}}" style="opacity:0;/* position:absolute; left:9999px;*/" checked>
  <label for="{{category}}"> {{ category }}</label><br>

  {% endfor %}

  <button type="submit">submit</button>


</form>












{% elif getUSerInfo%}

<form action="/user/info/" method="POST">
  {% csrf_token %}

Username:&emsp;&ensp;&nbsp;&emsp; <input id="username" type="text" name="username" value={{user.username}}><br><br>
First name:&emsp;&nbsp;&emsp; <input id="first_name" type="text" name="first_name" value="{{ user.first_name }}"><br><br>
Middle name:&emsp;&emsp; <input id="middle_name" type="text" name="middle_name" value="{{ user.middle_name }}"><br><br>
Last name:&emsp;&emsp;&emsp;&emsp; <input id="last-name" type="text" name="last_name" value="{{ user.last_name }}"><br><br>
email:&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; <input id="email" type="text" name="email" value="{{ user.email }}"><br><br>

Country:&emsp;&emsp;&emsp;&emsp;&emsp; <input id="country" type="text" name="country" value="{{ user.her_country}}"><br><br>

<br>!!{{message}}:<br><br>

phone number:&emsp; <input id="phone_number" type="text" name="phone_number" value="{{ user.phone_number }}"><br><br>
Relligion:&emsp;&emsp;&emsp;&emsp; <input id="relligion" type="text" name="relligion" value="{{ user.relligion }}"><br><br>
<button type="submit"> Submit</button>






<!--    <p>This is a &nbsp; regular space.</p> 
    <p>This is a &ensp; two spaces gap.</p> 
    <p>This is a &emsp; four spaces gap.</p> -->



{% else %}

<form action="/action_page.php">
  <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
  <label for="vehicle1"> I have a bike</label><br>
  <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
  <label for="vehicle2"> I have a car</label><br>
  <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
  <label for="vehicle3"> I have a boat</label><br><br>
  <input type="submit" value="Submit">
</form>


 <input type="text" name="search_term" maxlength="100" required="" id="id_search_term" placeholder="Search..">

  <button type="submit"><i class="fa fa-search"></i></button>
{% endif %}

user/templates/user/profile.html
Welcome!<br>
<!--Welcome, From Memes!!-->
{% if display_type == "/Upload/" %}
<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form }}
<input type="submit" value="Submit">
</form>
{% else %}

{% load static %}
<img class='img' src={% static profile_pic%} height=1000 width=500 alt='purnika' style="float:right;width:400px;height:500px;">
    
    {% if user %}

    Username: {{ user.username }}
    First_name: {{ user.first_name }}
    Middle_name: {{ user.middle_name }}
    Last_name: {{ user.last_name }}
    email: {{ user.email }} 
    Phone_number: {{ user.phone_number }} 
    Relligion: {{ user.relligion }}
    
    {% endif %}
{% endif %}